services:
  grafana:
    container_name: 'tamirsuliman-weathermap-panel'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-12.0.0}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/tamirsuliman-weathermap-panel
      - ./provisioning:/etc/grafana/provisioning
